settings:
  auto-join-instance: true
instance-event:
  chat: "<playerName()> message()"
  join: "ยง6 playerName() viens de rejoindre le serveur."
  quit: "ยง6 playerName() viens de quitter le serveur."
  death: "playerName() viens de mourir."