name: SubServer
version: '${project.version}'
main: com.stackmc.subserver.SubServer
api-version: '1.20.6'
depend: [SlimeWorldManager]
authors: [LoanSpac, Clooooud]
commands:
  subserver:
    description: "SubServer's main command"