name: SubServer
version: '${project.version}'
main: fr.loanspac.subserver.SubServer
api-version: '1.18'
authors: [ LoanSpac, Clooooud ]
commands:
  subserver:
    description: "SubServer's main command"

